### ISSUE TITLE
For validation: Same number by same person should only be entered once

### ISSUE THREAD

**Issue by DaniGr** [fzesch/lagesonum#1]
Actual:
If I submit the same number more than once both entries are accepted by the form and also entered in the database.

Expected:
Every user should only be allowed to enter any number once. Probably prevent with a cookie?
When the user enters the number more than once there should be an error according to "erroruniquenumber" in the loca doc.

Steps to Reproduce:
Query fantasy number (e.g. R567) to make sure it's not in the database yet
Enter fantasy number (e.g. R567) 3 times.
Query this number from the search page.
It is in the database 3 times.

**Comment by fzesch** [comment]
implemented with hash of browser characteristics
