### ISSUE TITLE
Put navbar in header.tpl

### ISSUE THREAD

**Issue by optikfluffel** [fzesch/lagesonum#14]
Putting the Navbar in `header.tpl` would be cool, so we only have to change it in one location and not every page template.
Then setting the `class="active"` for appropriate styling could be done client-side using jQuery (since it's already in here from Bootstrap) with something like this:

``` html
<script type="text/javascript">
  jQuery(document).ready(function() {
    jQuery('#navbar .nav a[href="' + this.location.pathname + '"]').parent().addClass('active');
  });
</script>
```

**Comment by danielberndt** [comment]
It should be fixed in one of my latest commits already :)

**Comment by danielberndt** [comment]
Oh and there's a more direct way to set the active set, via passing extra variables in the `%include` command
