### ISSUE TITLE
Return timestamp from DB as datetime (rather than string)

### ISSUE THREAD

**Issue by danielberndt** [fzesch/lagesonum#18]
In theory all you need to do is add this argument to the `.connect` method:

```
lagesonrdb = sqlite3.connect(DB_PATH, detect_types=sqlite3.PARSE_DECLTYPES)
```

however it was complaining here:

```
  File "/Users/danielberndt/workspace/tmp/lagesonum/lagesonum/bottle_app.py", line 99, in do_query
    result = cursor.execute(select_query, values).fetchall()
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sqlite3/dbapi2.py", line 68, in convert_timestamp
    datepart, timepart = val.split(" ")
```

**Comment by fzesch** [comment]
Kristian, kannst du dir das bei Gelegenheit mal anschauen?

**Comment by krother** [comment]
Ja, gerne.

**Comment by krother** [comment]
Hab's rausgefunden: die Timestamps werden schon mit mehreren Leerzeichen gespeichert, es darf aber nur eins drin vorkommen. 
Lösung: Statt time.asctime() das Modul datetime verwenden:

import time
datetime.datetime.now()

Code läuft bei mir seltsam, baue es deshalb nicht gleich ein.

**Comment by fzesch** [comment]
Ich habe es mal gemacht, Code läuft bei mir gut https://github.com/fzesch/lagesonum/commit/445ed8f23cc29432af03da8a6fc7ff85cdcc35e2

**Comment by danielberndt** [comment]
still returns a string for me: `AttributeError("'unicode' object has no attribute 'strftime'",)`

**Comment by fzesch** [comment]
Mit Py3 ?

**Comment by krother** [comment]
ja

---

Dr. Kristian Rother
(+49) 0176 3052 4691
www.academis.eu

Create Better Science!

Am 23. September 2015 07:58:10 +02:00, hat fzesch notifications@github.com geschrieben:

**Comment by fzesch** [comment]
@daniel, bei dir kommt der Fehler mit Py3?
