### ISSUE TITLE
Change text inputs to drop downs / virtual keyboard

### ISSUE THREAD

**Issue by DaniGr** [fzesch/lagesonum#19]
Actual:
Non Latin keyboards can't type in the numbers as they don't share the same alphabet.

Expected:
Add 4 dropdown menus instead of the text input fields so the input is independent from the keyboard.
[A-Z] [0-9] [0-9] [0-9]
There could also be a virtual keyboard instead, whatever is easier to do.

Steps to reproduce: 
Switch keyboard to Arabic and try to enter valid Numbers.

**Comment by fzesch** [comment]
I suppose, this concerns (for now) only the query_page, not the one where you enter numbers. Otherwise, entering multiple numbers can become rather cumbersome :)

**Comment by DaniGr** [comment]
I did mean both pages. If being able to enter more than 1 number at once is considered important, there can be more drop downs on this page.

**Comment by fzesch** [comment]
I would wait for the first field tests, whether input really is a problem. I have been told, that everybody having an arab keyboard and basic smartphone literacy can enter latin numbers.

**Comment by pitpalme** [comment]
I'd think that people having arabic keyboard, whether on smartphone or laptop, understanding the system, official display and webapp, should be able to switch keyboard layout for a moment to enter numbers.

Making it 4 select menus reduces UX to almost zero for those, that don't need it.
Adding 4 select menus in addition to input field will create a whole lot of effort to write code that keeps the than two ways to enter "in sync".

Additionally if this app's code base will be enabled to deal with different locations/places 4 select menus might not be the correct number, plus it's not necessarily [A-Z][0-9]{3}. This will make code a mess to maintain.

I'd postpone (and therefore for now: close) this issue, until relevance is proven and possible solution to concrete problem have been discussed carefully.
