### ISSUE TITLE
Select language based on browser preferences

### ISSUE THREAD

**Issue by fzesch** [fzesch/lagesonum#23]
Read browser preferences for languages and deliver the page in the language preferred by the user, if possible, in English otherwhise. 

Hint: usr_lang = str(request.environ.get('HTTP_ACCEPT_LANGUAGE', ''))

**Comment by danielberndt** [comment]
it seems like `default_locale` can't be set dynamically (i.e. can't be set in response to the request). It almost seems like `bottle_utils-i18n` doesn't really support this use case?

**Comment by fzesch** [comment]
Is there maybe a workaround? like imitating user selection of locale in the menu?

**Comment by danielberndt** [comment]
Maybe it is worth exploring another library. This one seems to support our use case:
https://github.com/iocast/bottle-i18n

> Running the above example it automatically loads the default language en if in the URL the langauge code or the HTTP_ACCEPT_LANGUAGE sent from the browser is missing.

**Comment by fzesch** [comment]
fixed by pit in current dev branch
