### ISSUE TITLE
Entering numbers results in Error 405

### ISSUE THREAD

**Issue by DaniGr** [fzesch/lagesonum#25]
Actual:
Entering numbers results in Error: 405 Method Not Allowed

Expected:
No errors

Steps to reproduce:
Go to http://lagesonum.de/en_US/enter (same with De language)
Enter any valid number
Observe error

**Comment by fzesch** [comment]
fixed https://github.com/fzesch/lagesonum/commit/d7c67db05b07753719b9880d13fc25f6806e37c8
