### ISSUE TITLE
Add Live display to show currently active numbers in real time

### ISSUE THREAD

**Issue by DaniGr** [fzesch/lagesonum#26]
Numbers to be shown there:
All numbers that have been entered 3 or more times and where the last time of entry is not older than X minutes.
For the "last time of entry age" it would be great to collect stats how long numbers are displayed in average. 
Until the stats are actually being collected, we should use 15 minutes as an "inactive" time setting. There should also be a link "history" where those numbers are then listed with a note "last seen".

**Comment by DaniGr** [comment]
Felix is at it and doing a very nice job!

**Comment by fzesch** [comment]
Ich denke, die bessere Variante wäre, alle Nummern nach Tagen und Uhrzeit geordnet auszugeben und dabei zu schreiben, wie oft sie eingegeben wurden.  Ansonsten müssen die Helfer immer wieder zahlen eingeben obwohl sie eigentlich besseres Vorhaben. Und am Wochenende kann man sonst auf der Seite gar nichts sehen.

Noch eine Frage zum Verwaltungsprozess: wie viel Zeit haben die Flüchtlinge, um nach Aufruf einer Nummer im entsprechenden Zimmer zu erscheinen?

**Comment by DaniGr** [comment]
I don't know what you mean by the comment that for the live display the helpers have to continuously enter numbers? The live display merely shows currently entered numbers which the helpers are entering anyways.
It's very cute to ask about an official process. It's chaos (see e.g. here: http://www.dw.com/de/reporter-deutschland-hilfe-f%C3%BCr-fl%C3%BCchtlinge-2015-09-26/e-18686179-9800) . There might be a process in theory but reality and with it the processes are changing every day! That's why I described a criteria for measuring the reality in the description. This will be much more accurate and reliable.

**Comment by fzesch** [comment]
Dani: "For the "last time of entry age" it would be great to collect stats how long numbers are displayed in average. Until the stats are actually being collected, we should use 15 minutes as an "inactive" time setting." --> I don't see how we can answer the question "how long numbers are displayed on average". This would require people to enter numbers continously. I think, the better solution is to group numbers by day and time when they were shown, but then you would need a search functions to find your number. Maybe we just wait until more input from the ground troups arrive...

**Comment by DaniGr** [comment]
The basic idea of the whole system is people entering numbers continuously. Good news: there is already a search function to find your own number: http://lagesonum.de/en_US/query ;)

**Comment by fzesch** [comment]
Fixed by Pit in current development branch
