### ISSUE TITLE
lazy_gettext does not work

### ISSUE THREAD

**Issue by fzesch** [fzesch/lagesonum#33]
Returned variables are not displayed on the website and HTML-expressions are escaped.
## Example for numbers:

``` html
Text in excel: "These numbers have been entered since %(since)s by at least %(min_count)s different persons."
Text in .po: "These numbers have been entered since %(since)s by at least %(min_count)s different persons."
Text in html: "These numbers have been entered since %(since)s by at least %(min_count)s different persons."
```

 In HTML: the values given by since and min_count should have been substituted by the returned variables from the def().
## Example for HTML-expressions:

``` html
excel: Mehr darüber kannst du in diesem <a href="http://www.taz.de/Wartezeiten-am-Berliner-Lageso/!5228958/">taz Artikel</a> lesen.
.po Mehr darüber kannst du in diesem <a href=\"http://www.taz.de/Wartezeiten-am-Berliner-Lageso/!5228958/\">taz Artikel</a> lesen.
HTML: Mehr darüber kannst du in diesem &lt;a href=&quot;http://www.taz.de/Wartezeiten-am-Berliner-Lageso/!5228958/&quot;&gt;taz Artikel&lt;/a&gt; lesen.
```
## lazy_gettext

It seems to me, that somehow, lazy_gettext is not working. A [similar problem appeared for somebody with Django on SO](http://stackoverflow.com/questions/24340527/how-to-return-a-lazy-translation-object-with-placeholders).
## it has worked before

As far as I can remember on [branch livedisplay](https://github.com/fzesch/lagesonum/blob/livedisplay/lagesonum/bottle_app.py) before the merge, everything worked fine. Also on master. After changing the msgid in .po from phrases to labels, things got messed up, somehow.

**Comment by fzesch** [comment]
Variable assignment needs to have mapping, e.g.

``` html
{{_('numberdisplaytxt')  % ({'min_count': min_count, 'since': since})}}
```

This solved at least one part of the problem...

**Comment by danielberndt** [comment]
um html auszuspucken braucht man ein `!` also z.B. so `{{!_('numberdisplaytxt')}}`
