### ISSUE TITLE
Move i18n to transifex

### ISSUE THREAD

**Issue by fzesch** [fzesch/lagesonum#37]
For painfree translations we should move to Transifex. I added our project there but I need help on the following steps:
- import existing translations
- set up deployment on server/github

**Comment by pitpalme** [comment]
Please raise this issue's priority.
Current way of translations is PITA.

Additionally, when refactoring i18n workflow, please consider renaming .po files, e.g. to "messages.po" - they're already in language aware directories, so no need to have different names for files.
Finally removing "messages.mo" from repository should be thought about. Those should be generated, where and when needed (e.g. "pybabel compile ..."). It's binary files, completely generated, which is two reasons why it shouldn't be dealt with in SCM.

**Comment by fzesch** [comment]
closed with merge of tx-branch, thanks pitpalme !
