### ISSUE TITLE
Help text for entry field about entering more than 1 number

### ISSUE THREAD

**Issue by DaniGr** [fzesch/lagesonum#49]
You can enter more than 1 number seperated by spaces but this is not clear to users. There needs to be a help text explaining this.

**Comment by fzesch** [comment]
Would it be enough to adopt the input example? "E.g. A123 BX99"

**Comment by DaniGr** [comment]
Yes, great idea!

**Comment by fzesch** [comment]
You can simply update the i18n file, then

**Comment by fzesch** [comment]
I adopted the i18n-label accordingly in the GoogleDoc
