### ISSUE TITLE
Caching leak

### ISSUE THREAD

**Issue by fzesch** [fzesch/lagesonum#51]
Some actually static content is loaded from external sites. Can we provide them on our site to increase speed and caching?

In the header.tpl this is:

``` html
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" crossorigin="anonymous"></script>
```

**Comment by pitpalme** [comment]
Caching should be best with integration from CDN, as resources are cached (I any) independent from website including it.

So theoretically 2, 3 or more sites including same bootstrap.min.css only first requires to load, others benefit.

OTOH local and offline development would be faster with self served resources, but most probably this is a minor issue ;)

**Comment by fzesch** [comment]
ok, then let's leave this for now.
