### ISSUE TITLE
www.lagesonum.de shows obsolete version

### ISSUE THREAD

**Issue by fzesch** [fzesch/lagesonum#59]
While on http://lagesonum.de the current release is available, an old version is on www.lagesonum.de . This old version needs to be removed and requests redirected to http://lagesonum.de

Since Felix just released prod, this is a rather urgent issue. Currently, the www-site is malfunctioning, many db-entries are missing (the http-version works fine, though)

**Comment by pitpalme** [comment]
Fixed.

www. pointed to beta. internally, because this one was loaded first and www. didn't match $server_name.
non-beta now is set to default_server.
