### ISSUE TITLE
Error: 405 Method Not Allowed with new config

### ISSUE THREAD

**Issue by fzesch** [fzesch/lagesonum#6]
Lokal und auf Server kann man keine Daten mehr eingeben (Error: 405 Method Not Allowed). Kannst du dir mal anschauen, warum?

**Comment by krother** [comment]
Hallo,

OK, ist behoben. Das war wegen der i18n.

Kristian

---

Dr. Kristian Rother
(+49) 0176 3052 4691
www.academis.eu

Create Better Science!

Am 14. September 2015, hat fzesch notifications@github.com geschrieben:

**Comment by fzesch** [comment]
fixed
