### ISSUE TITLE
Datenschutzerklärung finden/anpassen

### ISSUE THREAD

**Issue by fzesch** [fzesch/lagesonum#8]
Wir brauchen eine Datenschutzerklärung, die den gesetztlichen Anforderungen genügt. § 13 des Telemediengesetzes sieht vor: „der Diensteanbieter hat den Nutzer zu Beginn des Nutzungsvorgangs über Art, Umfang und Zwecke der Erhebung und Verwendung personenbezogener Daten sowie über die Verarbeitung seiner Daten zu informieren“. 

Umsetzung: Textbausteine suchen und anpassen.

**Comment by fzesch** [comment]
Danke für das Einfügen. Die Übersetzung ist vermutlich eher schwierig. Wollen wir sie einfach auf Deutsch lassen?

**Comment by DaniGr** [comment]
Maja

**Comment by DaniGr** [comment]
Herr Telefon, ich sagte "Ja" und nicht "Maja".... Immer diese neunmalklugen Maschinen!!
