### ISSUE TITLE
Arabic rendering

### ISSUE THREAD

**Issue by ffflorian** [fzesch/lagesonum#90]
When displaying languages written from the right to the left, you have to pay attention to the css to allow the font to be displayed from the right to the left, too.

The CSS attribute is

``` css
direction: rtl;
```

**Comment by pitpalme** [comment]
Is there any care taking of HTML attributes for "dir" necessary, or does CSS cover it all?

**Comment by ffflorian** [comment]
@pitpalme 

> Is there any care taking of HTML attributes for "dir" necessary, or does CSS cover it all?

Oh cool, I was not aware of this attribute. CSS covers it all, but we can also use the HTML attribute instead of the CSS attribute.

**Comment by jlev** [comment]
Be aware that when designing for RTL languages the entire structure of the site should be mirrored for prominence on the right: navigation buttons, list indicators, etc. A class on the body or main content div can help descendent selectors.
