### ISSUE TITLE
Telegram notifications

### ISSUE THREAD

**Issue by ffflorian** [fzesch/lagesonum#98]
For the Telegram notifications (which will be a Node.js application) we will send and expect the following JSON POST requests to and from the server:
#### When the app checks if a ticket exists

``` json
{
    "requestid": "4yX4h9HZg",
    "search": true,
    "ticket": "B123"
}
```
#### When the user subscribes to a ticket

``` json
{
    "requestid": "rUyI1NEbSA",
    "userid": 123456789,
    "language": "de_DE",
    "ticket": "B123",
    "subscribe": true
}
```
#### When the user unsubscribes from a ticket

``` json
{
    "requestid": "JSv4btdNHt",
    "userid": 123456789,
    "ticket": "B123",
    "subscribe": false
}
```
#### When the user unsubscribes from all tickets

``` json
{
    "requestid": "JSv4btdNHt",
    "userid": 123456789,
    "subscribe": false
}
```
#### When the user requests a list of their currently subscribed tickets

``` json
{
    "requestid": "JSv4btdNHt",
    "userid": 123456789,
    "list": true
}
```

The field `requestid` is for internal verification, it just needs to be returned.
#### When a user needs to be notified because their ticket was seen

``` json
{
    "userid": 123456789,
    "message": "Dein Ticket B123 wurde um 12:48 Uhr gesehen."
}
```
#### When the user requests a list of their currently subscribed tickets

``` json
{
    "requestid": "JSv4btdNHt",
    "userid": 123456789,
    "success": true,
    "data": {
        "tickets": [
            "B123",
            "X456"
        ]
    }
}
```
#### A failed request (e.g. because of a database error)

``` json
{
    "requestid": "rUyI1NEbSA",
    "success": false,
    "message": "Database error"
}
```

The field `message` will be sent to the developers. The user will be shown a more helpful status message.

The website link for subscribing is `https://telegram.me/Lagesonum_bot`.

**Comment by ffflorian** [comment]
By the way, the repo of the app is [here](https://github.com/derhuerst/lagesonum-telegram).

**Comment by jlev** [comment]
- [x] create telegram_confirmed field on Subscription
- [x] create TelegramNotificationView at notifications.telegram.views
- [ ] json request

**Comment by derhuerst** [comment]
Is this already implemented?

**Comment by ffflorian** [comment]
@derhuerst No, we are still waiting for @jlev to finish the implementation on the server side.

**Comment by jlev** [comment]
Sorry for the radio silence, I've been recovering from travel and catching up on client work. I added a stub implementation on the sms_notification branch, but probably won't be able to flesh it out fully for a few weeks.

My next task on the project is switching from Twilio to the new SMS provider, Lox24. Feel free to update the ticket if you think this is a higher priority.
